name: Build Windows GROMACS with CUDA 12.4.1

on:
  push:
    branches:
      - master

env:
  gmxversion: "2025.0-beta"
  gmxcompileto: C:/Temp/gmxfiles
  fftwversion: "3.3.9"
  fftwcompileto: C:/Temp/fftw3

jobs:
  Windows:
    runs-on: windows-2022

    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download Gromacs and FFTW
        shell: bash
        env:
          gmxdownloadlink: https://ftp.gromacs.org/gromacs/gromacs-${{env.gmxversion}}.tar.gz
          fftwlink: https://fftw.org/fftw-${{env.fftwversion}}.tar.gz
        run: |
          curl -Lfo gromacs_src.tar.gz ${{ env.gmxdownloadlink }}
          tar xf gromacs_src.tar.gz
          sed -i 's/${CMAKE_CXX17_STANDARD_COMPILE_OPTION}/-std c++17/g' "gromacs-${{ env.gmxversion }}/cmake/gmxManageNvccConfig.cmake"
          # remove 35 and 37 for cuda 12
          ver=${{ env.gmxversion }}
          if [[ ${ver%%.*} -lt 2024 ]];then
            sed -i '/compute_35\|compute_37/d' "gromacs-${{ env.gmxversion }}/cmake/gmxManageNvccConfig.cmake"
          fi
          curl -Lfo fftw_src.tar.gz ${{ env.fftwlink }}
          tar xf fftw_src.tar.gz
          
      - name: Install CUDA Toolkit
        run: |
          mkdir -p "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4"
          mkdir -p "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\extras"
          choco install unzip -y
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cudart/windows-x86_64/cuda_cudart-windows-x86_64-12.4.127-archive.zip"
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/windows-x86_64/cuda_nvcc-windows-x86_64-12.4.131-archive.zip"
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cccl/windows-x86_64/cuda_cccl-windows-x86_64-12.4.127-archive.zip"
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/libcufft/windows-x86_64/libcufft-windows-x86_64-11.2.1.3-archive.zip"
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/visual_studio_integration/windows-x86_64/visual_studio_integration-windows-x86_64-12.4.127-archive.zip"
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_profiler_api/windows-x86_64/cuda_profiler_api-windows-x86_64-12.4.127-archive.zip"
          unzip '*.zip' -d "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4"
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\cuda_cudart-windows-x86_64-12.4.127-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\cuda_nvcc-windows-x86_64-12.4.131-archive\*"   "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\cuda_cccl-windows-x86_64-12.4.127-archive\*"   "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\libcufft-windows-x86_64-11.2.1.3-archive\*"    "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\cuda_profiler_api-windows-x86_64-12.4.127-archive\*"    "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\visual_studio_integration-windows-x86_64-12.4.127-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\extras" /E /I /H /Y

          echo 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\libnvvp' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo 'CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4' | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          echo 'CUDA_PATH_V12_4=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4' | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Copy MSBuildExtensions
        run: |
          Copy-Item -Path "$env:CUDA_PATH\extras\visual_studio_integration\MSBuildExtensions\*" -Destination "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\BuildCustomizations\" -Force
          Copy-Item -Path "$env:CUDA_PATH\extras\visual_studio_integration\MSBuildExtensions\*" -Destination "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations\" -Force

      - name: Compile FFTW single precision
        shell: pwsh
        run: |
          Set-Location fftw-${{ env.fftwversion }} 
          New-Item -ItemType Directory -Name build
          Set-Location build
          cmake .. -DCMAKE_INSTALL_PREFIX=${{ env.fftwcompileto }} -DENABLE_AVX=ON -DENABLE_AVX2=ON -DENABLE_SSE2=ON -DENABLE_THREADS=ON -DWITH_COMBINED_THREADS=ON -DENABLE_FLOAT=ON -DBUILD_SHARED_LIBS=ON -G "Visual Studio 17 2022" -T "v142" -A "x64"
          cmake --build . --target INSTALL --config Release -- "-maxCpuCount" "-p:CL_MPCount=3"
          Set-Location ..\..
          Remove-Item -Path fftw-${{ env.fftwversion }} -Force -Recurse

      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          # must use v142 to avoid compile errors for ninja about calc_verletbuf.cpp code
          toolset: 14.29

      - name: Compile GROMACS CUDA
        shell: bash
        run: |
          cd gromacs-${{ env.gmxversion }} && mkdir build && cd build
          choco install ninja
          ver=${{ env.gmxversion }}
          if [[ ${ver%%.*} -ge 2025 ]];then
            # patch openmp and gpu issue in MSVC and use MSBuild 
            cd ../../ && patch -p0 < patch/2025-beta-gpu.patch && cd gromacs-${{ env.gmxversion }}/build
            # cmake 3.30 has bug for gmx2025
            pip install cmake==3.28
            which cmake
            cmake .. -DCMAKE_INSTALL_PREFIX=${{ env.gmxcompileto }} -DCMAKE_PREFIX_PATH=${{ env.fftwcompileto }} -DGMX_SIMD=AVX2_256 -DGMX_GPU=CUDA -DCMAKE_BUILD_TYPE=Release -DGMX_USE_PLUMED=OFF -DGMX_USE_COLVARS=NONE -T "v142" -A "x64"
            cmake --build . --target INSTALL --config Release -- "-maxCpuCount" "-p:CL_MPCount=3"
          elif [[ ${ver%%.*} -eq 2024 ]];then
            cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=${{ env.gmxcompileto }} -DCMAKE_PREFIX_PATH=${{ env.fftwcompileto }} -DGMX_SIMD=AVX2_256 -DGMX_GPU=CUDA -DCMAKE_BUILD_TYPE=Release 
            sed -i 's/-MD/-MT/g' build.ninja
            ninja install -j4
          else
            # turn off GMX_USE_SIMD_KERNELS when gmx < 2024
            cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=${{ env.gmxcompileto }} -DCMAKE_PREFIX_PATH=${{ env.fftwcompileto }} -DGMX_SIMD=AVX2_256 -DGMX_GPU=CUDA -DCMAKE_BUILD_TYPE=Release -DGMX_USE_SIMD_KERNELS=OFF 
            sed -i 's/-MD/-MT/g' build.ninja
            ninja install -j4
          fi
          cd ../../
          rm -rf gromacs-${{ env.gmxversion }}

      - name: Copy DLLs and Test
        shell: pwsh
        run: |
          Copy-Item -Path "${{ env.CUDA_PATH }}\bin\cufft64_*.dll" -Destination "${{ env.gmxcompileto }}\bin\" -Force
          Copy-Item -Path "${{ env.fftwcompileto }}\bin\*.dll" -Destination "${{ env.gmxcompileto }}\bin\" -Force
          Set-Location ${{ env.gmxcompileto }}
          Set-Location ${{ env.gmxcompileto }}\bin
          .\gmx.exe -version

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: gmx_bins
          path: ${{ env.gmxcompileto }}


  # refer to https://github.com/endless-sky/endless-sky/blob/master/.github/workflows/cd.yaml
  Release:
    needs: [Windows]
    runs-on: ubuntu-20.04

    env:
        RELEASE_COMMAND: release
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_TAG: bleed

    steps:
      - uses: actions/checkout@v3

      - name: Install github-release
        run: |
          go install github.com/github-release/github-release@latest
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      
      - name: Set environment variables
        run: |
          echo "RELEASE_TAG=bleed" >> $GITHUB_ENV
          echo "TIME=$(date -u '+%Y.%m.%d')" >> $GITHUB_ENV
          echo "GITHUB_USER=$( echo ${{ github.repository }} | cut -d/ -f1 )" >> $GITHUB_ENV
          echo "GITHUB_REPO=$( echo ${{ github.repository }} | cut -d/ -f2 )" >> $GITHUB_ENV

      # - name: Move/Create continuous tag
      #   run: |
      #     git tag --force ${{ env.RELEASE_TAG }} ${{ github.sha }}
      #     git push --tags --force
      
      - name: Check continuous release status
        run: |
          if ! github-release info -t ${{ env.RELEASE_TAG }} > /dev/null 2>&1; then
            echo "RELEASE_COMMAND=release" >> $GITHUB_ENV
          else
            echo "RELEASE_COMMAND=edit" >> $GITHUB_ENV
          fi
      
      - name: Setup continuous release
        run: |
          DESCRIPTION="Triggered on $(date -u '+%Y/%m/%d, %H:%M') UTC by commit ${{ github.sha }} (@${{ github.actor }})
          This is an automated build of the latest source. It may be unstable or even crash, corrupt your save or eat your kitten. Use with caution!
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          github-release ${{env.RELEASE_COMMAND}} --tag ${{ env.RELEASE_TAG }} --name "Bleed Release" --description "$DESCRIPTION" --pre-release
      

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: gmx_bins

      - name: Package Windows artifact to release
        env:
          OUTPUT_TAR: GROMACS-${{ env.gmxversion }}_GPU.tar.gz
        run: |
          ls -alt
          tar -czvf ${{env.OUTPUT_TAR}} share include bin
          github-release upload --tag ${{ env.RELEASE_TAG }} --replace --name ${{env.OUTPUT_TAR}} --file ${{env.OUTPUT_TAR}}
