name: Build Windows GROMACS with ROCM

on:
  push:
    branches:
      - master

env:
  gmxversion: "2024.4"
  gmxcompileto: C:/Temp/gmxfiles
  fftwversion: "3.3.9"
  fftwcompileto: C:/Temp/fftw3
  ROCM_PATH: C:\Program Files\AMD\ROCm\6.1

jobs:
  Windows:
    runs-on: windows-2022

    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download Gromacs and FFTW
        shell: bash
        env:
          gmxdownloadlink: https://ftp.gromacs.org/gromacs/gromacs-${{env.gmxversion}}.tar.gz
          fftwlink: https://fftw.org/fftw-${{env.fftwversion}}.tar.gz
        run: |
          curl -Lfo gromacs_src.tar.gz ${{ env.gmxdownloadlink }}
          tar xf gromacs_src.tar.gz
          curl -Lfo fftw_src.tar.gz ${{ env.fftwlink }}
          tar xf fftw_src.tar.gz
          
      - name: Install ROCM HIP SDK
        run: |
          Get-ComputerInfo | Format-Table CsSystemType,OSName,OSDisplayVersion
          curl -Lfo setup.exe https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-24.Q3-WinSvr2022-For-HIP.exe
          Start-Process setup.exe -ArgumentList '-install','-log',"${env:USERPROFILE}\installer_log.txt" -NoNewWindow -Wait

          dir "${{env.ROCM_PATH}}"
          


      - name: Build ROCM GROMACS
        shell: pwsh
        if: ${{ success() }}
        run: |
          dir "${{env.ROCM_PATH}}\bin"
          choco install ninja sed

          Set-Location gromacs-${{ env.gmxversion }}
          mkdir build 
          Set-Location build

          cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=${{ env.gmxcompileto }} -DCMAKE_PREFIX_PATH=${{ env.fftwcompileto }};"${{env.ROCM_PATH}}" -DGMX_SIMD=AVX2_256 -DGMX_GPU=SYCL -DGMX_SYCL_HIPSYCL=ON -DHIPSYCL_TARGETS="hip:gfx1100" -DCMAKE_C_COMPILER="" -DCMAKE_CXX_COMPILER="" -DCMAKE_BUILD_TYPE=Release 

          sed -i 's/-MD/-MT/g' build.ninja
          ninja install -j4; if (-not $?) { ninja install -j1 }

          Set-Location ../..
          Remove-Item -Path gromacs-${{ env.gmxversion }} -Recurse -Force

      - name: Copy DLLs and Test
        shell: pwsh
        run: |
          Copy-Item -Path "${{ env.ROCM_PATH }}\bin\amdhip64_*.dll" -Destination "${{ env.gmxcompileto }}\bin\" -Force
          Copy-Item -Path "${{ env.fftwcompileto }}\bin\*.dll" -Destination "${{ env.gmxcompileto }}\bin\" -Force
          Set-Location ${{ env.gmxcompileto }}
          Set-Location ${{ env.gmxcompileto }}\bin
          .\gmx.exe -version

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: gmx_rocm_bins
          path: ${{ env.gmxcompileto }}
