name: Build Linux GROMACS with ROCM

on:
  push:
    branches:
      - master

env:
  gmxversion: "2024.4"
  gmxcompileto: /home/gmxfiles
  adcppto: /home/adcpp
  # must be 5.7
  ROCM_PATH: /opt/rocm

jobs:
  Ubuntu:
    runs-on: ubuntu-22.04

    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache ROCM 5.7
        id: cache-rocm
        uses: actions/cache@v4
        with:
          path: ${{env.ROCM_PATH}}
          key: ${{runner.os}}-rocm-5.7

      - name: Install ROCM
        run: |
          sudo apt update
          wget -O amdgpu-install.deb http://repo.radeon.com/amdgpu-install/5.7/ubuntu/jammy/amdgpu-install_5.7.50700-1_all.deb
          sudo apt install ./amdgpu-install.deb -y
          amdgpu-install -y --usecase=rocm,hiplibsdk,graphics --no-dkms
          # test
          rocminfo
          
