name: Build Linux GROMACS with ROCM

on:
  push:
    branches:
      - master

env:
  gmxversion: "2024.4"
  gmxcompileto: /home/gmxfiles
  adcppto: /home/adcpp
  # must be 5.7
  ROCM_PATH: /opt/rocm

jobs:
  Ubuntu:
    runs-on: ubuntu-22.04

    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache ROCM 5.7
        id: cache-rocm
        uses: actions/cache@v4
        with:
          path: ${{env.ROCM_PATH}}
          key: ${{runner.os}}-rocm-5.7

      - name: Install ROCM
        run: |
          apt update
          wget -O amdgpu-install.deb http://repo.radeon.com/amdgpu-install/5.7/ubuntu/jammy/amdgpu-install_5.7.50700-1_all.deb
          apt install ./amdgpu-install.deb -y
          amdgpu-install -y --usecase=rocm,hiplibsdk
          # test
          rocminfo

      - name: Install Adaptive
        run: |
          wget https://github.com/AdaptiveCpp/AdaptiveCpp/archive/refs/tags/v24.06.0.tar.gz
          tar -xf v24.06.0.tar.gz
          cd AdaptiveCpp-24.06.0 && mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=${{env.adcppto}} \
                   -DCMAKE_BUILD_TYPE=Release \
                   -DCMAKE_C_COMPILER=${{env.ROCM_PATH}}/llvm/bin/clang \
                   -DCMAKE_CXX_COMPILER=${{env.ROCM_PATH}}/llvm/bin/clang++ \
                   -DWITH_ROCM_BACKEND=ON \
                   -DROCM_PATH=${{env.ROCM_PATH}} \
                   -DLLVM_DIR=${{env.ROCM_PATH}}llvm/lib/cmake/llvm
          make -j4 install
          cd ../..
      
      - name: Install GROMACS
        run: |
          wget https://ftp.gromacs.org/gromacs/gromacs-${{env.gmxversion}}.tar.gz
          tar -xf gromacs-${{env.gmxversion}}.tar.gz
          cd gromacs-${{env.gmxversion}} && mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=${{env.gmxcompileto}} \
                   -DCMAKE_BUILD_TYPE=Release \
                   -DCMAKE_PREFIX_PATH=${{env.adcppto}} \
                   -DCMAKE_C_COMPILER=${{env.ROCM_PATH}}/llvm/bin/clang \
                   -DCMAKE_CXX_COMPILER=${{env.ROCM_PATH}}/llvm/bin/clang++ \
                   -DGMX_SIMD=AVX2_256 -DGMX_GPU=SYCL -DGMX_SYCL=ACPP \
                   -DACPP_TARGETS="hip:gfx1100,gfx1101,gfx1102" \
                   -DGMX_BUILD_OWN_FFTW=ON 
          make -j4 install
          source ${{env.gmxcompileto}}/bin/GMXRC
          gmx --version

