name: Test pwd

on:
    push:
      branches:
        - master

jobs:
    Ubuntu:
        strategy:
            matrix:
              os: [20.04, 22.04, 24.04]

        runs-on: ubuntu-${{matrix.os}}
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: mkdir
              run: |
                echo "pwd after: $(pwd)"
                df -h
                sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php
                df -h

